# Generated by Django 4.2.11 on 2024-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBizprocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(unique=True)),
                ('process_name', models.CharField(max_length=200)),
            ],
        ),
    ]
