# Generated by Django 4.2.11 on 2024-04-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallInfo',
            new_name='MyCallInfo',
        ),
    ]
