# Generated by Django 4.2.11 on 2024-04-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calls', '0003_mycallinfo_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycallinfo',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
