# Generated by Django 4.2.11 on 2024-04-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calls', '0005_rename_entity_id_mycallinfo_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycallinfo',
            name='lead_id',
        ),
    ]
