# Generated by Django 4.2.11 on 2024-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calls', '0006_remove_mycallinfo_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycallinfo',
            name='lead_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
